WIP: Initial commit
DEFRA/coreai-mcu-responses pull request #11
Opened 2024-04-17 07:36 UTC by BarryGeeDefra

# **What this PR does / why we need it**:
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#213700 and builds on #3376 (link to ADO Build ID URL)*

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [ ] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [ ] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests
- [ ] Version number in **package.json** has been updated

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-04-18 15:53 UTC, sfitz42 requested changes
Just a few suggestions.

2024-04-18 15:53 UTC, sfitz42 commented on app/config/storage.js
> +  responsesContainer: Joi.string().default('responses')
I would maybe call this `finalisedresponses`, just to avoid any confusion.

2024-04-18 15:53 UTC, sfitz42 commented on app/mappers/response-metadata.js
Don't think we need this as we're not using snake case anywhere.

2024-04-18 15:53 UTC, sfitz42 commented on app/storage/response-repo.js
> +const saveResponseBlob = async ({
Rather than defining the object here could we just have `response` and deconstruct inside the function?

Might be worth just passing in the parameters without an object.

2024-04-18 15:53 UTC, sfitz42 commented on app/storage/response-repo.js
> +      status: 'sent'
Could we pass the metadata object in as a parameter? Just in case we need more items in future.

Might be good to get the latest metadata and merge the objects in case of updates.

2024-04-19 08:37 UTC, sebhoron reviewed
LGTM, just correct the status code and the version needs a bump

2024-04-19 09:22 UTC, sebhoron submitted a review, later dismissed

2024-04-19 10:12 UTC, sebhoron approved these changes
LGTM

2024-04-22 06:30 UTC, merged